title : Xing
tagline: Blog Tagline
author :
  name : Xing Wong
  email : huang1986xing@gmail.com
  github : hxpax
  twitter : xing
  feedburner : xing

navigation :
#  - archive.html
  - tags.html
#  - categories.html
#  - pages.html
  - about.md
  
